name: CD

on:
  release:
    types: 
    - published

jobs:

  ubuntu_x86_64:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ARCH: x86_64 
      OUTPUT: endless-sky-amd64.tar.gz
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo rm /etc/apt/sources.list.d/* && sudo dpkg --clear-avail # Speed up installation and get rid of unwanted lists
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libsdl2-dev libpng-dev libjpeg-turbo8-dev libopenal-dev libmad0-dev libglew-dev libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev scons
      - name: Build Application
        run: scons -j $(nproc)
      - name: Package Application
        run: tar -cf ${{ env.OUTPUT }} sounds images/ data/ license.txt keys.txt icon.png endless-sky credits.txt copyright changelog
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: ${{ env.OUTPUT }}
          path: ${{ env.OUTPUT }}
      - name: Upload Application
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.OUTPUT }}
          asset_name: ${{ env.OUTPUT }}
          asset_content_type: application/octet-stream


  appimage_x86_64:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ARCH: x86_64
      OUTPUT: endless-sky-x86_64.AppImage
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo rm /etc/apt/sources.list.d/* && sudo dpkg --clear-avail # Speed up installation and get rid of unwanted lists
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libsdl2-dev libpng-dev libjpeg-turbo8-dev libopenal-dev libmad0-dev libglew-dev libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev scons
      - name: Build Application
        run: |
          cp icons/icon_512x512.png endless-sky.png # We need an icon file with this name
          scons -j $(nproc) install DESTDIR=AppDir 
          # Inside an AppImage, the executable is a link called "AppRun" at the root of AppDir/.
          # Keeping the data files next to the executable is perfectly valid, so we just move them to AppDir/ to avoid errors.
          mv AppDir/usr/local/share/games/endless-sky/* AppDir/
      - name: Build AppImage
        run: |
          curl -L https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage -o linuxdeploy && chmod +x linuxdeploy
          ./linuxdeploy --appdir AppDir -e endless-sky -d endless-sky.desktop -i endless-sky.png --output appimage
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: ${{ env.OUTPUT }}
          path: ${{ env.OUTPUT }}
      - name: Upload AppImage
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.OUTPUT }}
          asset_name: ${{ env.OUTPUT }}
          asset_content_type: application/octet-stream

  build_windows:
    runs-on: windows-latest
    env:
        DIR_MINGW64: C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\x86_64-w64-mingw32
        DIR_ESLIB: .\dev64
        OUTPUT: EndlessSky-win64.zip 
    steps:
    - uses: actions/checkout@v2
    - name: Fetch development libraries
      run: |
        Invoke-WebRequest https://endless-sky.github.io/win64-dev.zip -OutFile win64-dev.zip
        Expand-Archive win64-dev.zip -DestinationPath . -Force
        Remove-Item win64-dev.zip
    - name: Compile
      run: |
        make -e -f .winmake -j ($(Get-CIMInstance -Class 'CIM_Processor').NumberOfLogicalProcessors)
        COPY .\bin\pkgd\EndlessSky.exe EndlessSky.exe
        COPY ".\dev64\bin\*.dll" .
        COPY C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\x86_64-w64-mingw32\lib\libgcc_s_seh-1.dll .
        COPY C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\x86_64-w64-mingw32\lib\libstdc++-6.dll .
        COPY C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\x86_64-w64-mingw32\lib\libwinpthread-1.dll .
    - name: Package Application
      run: 7z a ${{ env.OUTPUT }} .\sounds\ .\images\ .\data\ *.dll license.txt keys.txt icon.png EndlessSky.exe credits.txt copyright changelog
    - name: Upload Application
      uses: actions/upload-release-asset@v1.0.2
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ env.OUTPUT }}
        asset_name: ${{ env.OUTPUT }}
        asset_content_type: application/octet-stream
