name: Setup Nightly CD

on:
  push

jobs:
  setup:
    runs-on: [ubuntu-latest]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Remove old Release
      run: |
        echo ${{ github.repository }}
        RELEASE_ID=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases | jq  '.[] | select(.tag_name == "nightly") | .id')
        echo $RELEASE_ID
        curl -X DELETE https://api.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID
        curl -X DELETE https://api.github.com/git/refs/tag /repos/${{ github.repository }}/git/refs/tags/nightly
    - name: Create Release
      uses: actions/create-release@v1
      with:
        tag_name: nightly
        release_name: Continuous Nightly Build
        body: TBD
        prerelease: true
