name: Setup Nightly CD

on:
  push

jobs:
  setup:
    runs-on: [ubuntu-latest]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Create Release
      uses: actions/create-release@v1
      with:
        tag_name: nightly
        release_name: Continuous Nightly Build
        body: TBD
        prerelease: true
